config/routes.rb
Rails.application.routes.draw do

	root 'homes#top'
	devise_for :users
	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :relationships
	resources :books do
		resources :favorites, only: [:create, :destroy]
		resources :book_comments
	end
	get '/home/about',to: 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites
	has_many :favorite_users, through: :favorites, source: :user
	has_many :book_comments
	validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :book_comment, presence: true, length: { maximum: 1000 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :following, class_name: "User"
	validates :follower_id, presence: true
	validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  def already_favorite?(book)
  	self.favorites.exists?(book_id: book.id)
  end
  has_many :book_comments, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships,foreign_key: "following_id", class_name: "Relationship",dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end


  validates :name, presence: true,length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
  	user_path(current_user)
  end

  def after_sign_out_path_for(resource)
  	root_path
  end

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])

  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
  	@book_comment = BookComment.new(book_comment_params)
  	@book_comment.user_id = current_user.id
  	@book_comment.book_id = params[:book_id].to_i
  	if @book_comment.save
  		redirect_back(fallback_location: books_path)
  	else
  		redirect_back(fallback_location: book_path(params[:book_id].to_i))
  	end
  end

  def destroy
  	@book_comment = BookComment.find_by(id: params[:id],book_id: params[:book_id])
  	@book_comment.destroy
  	redirect_back(fallback_location: book_path)
  end

  private
  def book_comment_params
  	params.require(:book_comment).permit(:book_comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	def show
		@book_new = Book.new
		@book = Book.find(params[:id])
		@books = Book.all
		@book_comment = BookComment.new
		@book_comments = @book.book_comments
		@user = @book.user
	end
	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "successfully"
			redirect_to book_path(@book)
		else
			@books = Book.all
			flash[:notice] = "error"
			render action: :index
		end
	end

	def edit
		@book =Book.find(params[:id])
		if current_user.id != @book.user_id
	 		redirect_to books_path
	 	end
	end

	def update
	 	@book = Book.find(params[:id])
	 	@book.update(book_params)
	 	if @book.save
			flash[:notice] = "successfully"
			redirect_to book_path(@book)
		else
			@book = Book.find(params[:id])
			flash[:notice] = "error"
			render action: :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
    end
    private

	def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!
  def create
  	@favorite = current_user.favorites.create(book_id: params[:book_id])
  	 redirect_back(fallback_location: books_path)
  end

  def destroy
  	@favorite =Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
  	@favorite.destroy
  	redirect_back(fallback_location: book_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
    end

    def about
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		@user = User.find(params[:relationship][:following_id])
		current_user.follow!(@user)
		# redirect_to @user
		redirect_to request.referer
	end

	def destroy
		@user = Relationship.find(params[:id]).following
		current_user.unfollow!(@user)
		# redirect_to @user
		redirect_to request.referer
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	 	@book = Book.new
	 	@user = User.find(params[:id])
	end

	def index
	 	@book = Book.new
	 	@users =User.all
	 	@user = current_user
	end

	def edit
	 	@user = User.find(params[:id])
	 	if current_user != @user
	 		redirect_to user_path(current_user)
	 	end
	end

	def update
	 	@user = User.find(params[:id])
	 	if @user.update(user_params)
	 	   flash[:notice] = "successfully"
	 	   redirect_to user_path(current_user)
	 	else
	 		flash[:notice] = "error"
			render action: :edit
		end
	end

	def following
		@user = User.find(params[:id])
		@users = @user.followings
		render 'show_follow'
	end

	def followers
		@user = User.find(params[:id])
		@users = @user.followers
		render 'show_follower'
	end


	private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
		user == current_user
	end
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class= "container">
<div class= "row">
<div class= "col-md-6 col-md-offset-3 ">
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(@book) do |f| %>
  <div class= "row field">
  	<h4>Title</h4>
  		<%= f.text_field :title, class: "col-xs-12" %>
　</div>
<div class= "row field">
  <h4>Body</h4>
  <%= f.text_area :body, class: "col-xs-12" %>
</div>
  <br><%= f.submit 'Update Book', class: "btn btn-default", class: "col-xs-12" %>
  <br><%=link_to 'Show', book_path %> <%=link_to 'Back', books_path %>
 <% end %>

</div>
</div>
</div>



<div class="col-md-4 col-md-offset-8">
<p>CopyRight Infratop.inc</p>
</div>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class= "container">
<div class= "row">
<div class= "col-md-3 ">
<h2>User info</h2>
<%= attachment_image_tag current_user, :profile_image, :fill, 70, 70, format: 'jpeg',fallback: "no_image.jpg", size:'70x70' %>
<table class="table">
	<tbody>
		<tr>
			<td>name</td>
			<td><%= current_user.name %></td>
		</tr>
		<tr>
			<td>introduction</td>
			<td><%= current_user.introduction %></td>
		</tr>
		<tr>
			<td><%= render 'users/stats' %></td>
			<td><%= render 'users/follow_form' %></td>

		</tr>
	</tbody>
 </table>
<%= link_to edit_user_path(current_user) do %>
<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_9733" aria-hidden="true"></span> 
<% end %>
<h2>New book</h2>
<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :title, class: "col-xs-12" %>

<h4>Opinion</h4>
<%= f.text_area :body, class: "col-xs-12" %>

<%= f.submit 'Create Book', class: "btn btn-default col-xs-12" %>

<% end %>
</div>

<div class="col-md-9">
	<h2>Books</h2>
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
			</tr>
		</thead>
		<tbody>
			<% @books.each do |book| %>
				<tr>
					<td class="col-md-3">
						<%= link_to user_path(book.user) do %>
						<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "no_image.jpg", size:'50x50' %>
						<% end %>
					</td>
					<td class="col-md-3"><%= link_to book.title, book_path(book) %> </td>
					<td class="col-md-3"><%= book.body %></td>
					<td class="col-md-3">
						<%if current_user.already_favorite?(book) %>
							<%= button_to 'いいねを取り消す', book_favorite_path(id: book.favorites, book_id:book), method: :delete %>
						<% else %>
							<%= button_to 'いいね', book_favorites_path(book) %>
						<% end %>
						いいね数: <%= book.favorites.count %>
						コメント数: <%= book.book_comments.count %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
</div>
</div>
<div class="col-md-4 col-md-offset-8">
<p>CopyRight Infratop.inc</p>
</div>

</div>

</div>

app/views/books/show.html.erb
<% if @book_new.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<div class= "container">
 <div class= "row">
  <div class= "col-md-3 ">

<h2>User info</h2>
<%= attachment_image_tag @book.user, :profile_image, :fill, 70, 70, format: 'jpeg',fallback: "no_image.jpg", size:'70x70' %>

		<table class="table">
			<tbody>

				<tr>
					<td>name</td>
					<td><%= @book.user.name %></td>
				</tr>
				<tr>
					<td>introduction</td>
					<td><%= @book.user.introduction %></td>
				</tr>
				<tr>
					<td><%= render 'users/stats'%></td>
					<td><%= render 'users/follow_form' %></td>
				</tr>
			</tbody>
		 </table>

<%= link_to edit_user_path(@book.user) do %>
<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_9733" aria-hidden="true"></span> 
<% end %>

<h2>New book</h2>
<%= form_for(@book_new) do |f| %>

<h4>Title</h4>
<%= f.text_field :title, class: "col-xs-12" %>

<h4>Opinion</h4>
<%= f.text_area :body, class: "col-xs-12" %>

<%= f.submit 'Create Book', class: "btn btn-default col-xs-12" %>

<% end %>
</div>

<div class="col-md-9">
	<h2>Book dateil</h2>
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
				<tr>
					<td class="col-md-2"><%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "no_image.jpg", size:'50x50' %><br><%= link_to @book.user.name, user_path(@book.user) %></td>
					
					<td class="col-md-2"><%= @book.title %></td>
					<td class="col-md-2"><%= @book.body %></td>
					<td class="col-md-3"><% if current_user.already_favorite?(@book) %>
						  <%= button_to 'いいねを取り消す', book_favorite_path(@book), method: :delete %>
						<% else %>
						  <%= button_to 'いいね', book_favorites_path(@book) %>
						<% end %>
						件数: <%= @book.favorites.count %>
					</td>
				<%if @book.user == current_user  %>

					<td class="col-md-1"><%= link_to "Edit", edit_book_path(@book), class: "btn btn-default" %></td>
					<td class="col-md-2"><%= link_to "Destroy", book_path(@book), class: "btn btn-default", method: :delete,"data-confirm" => "本当に消しますか？" %></td>
				<% end %>
				</tr>
		</tbody>
	</table>
	<table class="table">
		<tbody>
				<tr>
					<td><%= form_for [@book,@book_comment] do |f| %>
							<%= f.text_field :book_comment,class: "col-md-12 comment" %>
							<br>
							<%= f.submit 'コメントする',class: "pull-right" %>
						<% end %>
					</td>
				</tr>
				<tr>
					<td>
						コメント一覧<br>
						件数: <%= @book.book_comments.count %>
					</td>
				</tr>
				<tr>
					<td><% @book_comments.each do |c| %>
							<div>
								<%= c.book_comment %>
							<%if c.user_id == current_user.id  %>
								<%= button_to '削除', book_book_comment_path(@book.id, c.id), method: :delete %>
							<% end %>
								<hr>
							</div>
						<% end %>
					</td>
				</tr>
		</tbody>
	</table>


</div>
</div>
</div>
<div class="col-md-4 col-md-offset-8">
<p>CopyRight Infratop.inc</p>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<div class="col-md-11 col-md-offset-1">
	<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>
<div class="col-md-4 col-md-offset-8">
<p>CopyRight Infratop.inc</p>
</div>

app/views/homes/top.html.erb
 <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
<div class= "container">
<div class= "row">
<div class= "col-md-6 col-md-offset-3 ">

  <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</p>
<p>you can share and exchange your opinions , inpressions , and emotions<br>about various books!</p>
<p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
<p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>

</div>
</div>
</div>

<div class="col-md-4 col-md-offset-8">
<p>CopyRight Infratop.inc</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <p class="title">Bookers</p>
    <nav class= "nav">
      
      <% if user_signed_in? %>

      <ul>
        <div class= "nav-list">
          <li class= "nav-list-item">
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span><span> </span>
            <%= link_to "Home", user_path(current_user) %>
          </li>
        </div>
        <div class= "nav-list">
          <li class= "nav-list-item">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span><span> </span>
            <%= link_to "Users", users_path %>
          </li>
        </div>
        <div class= "nav-list"><li class= "nav-list-item"><span class="glyphicon glyphicon-book" aria-hidden="true"></span><span> </span><%= link_to "Books", books_path %></li></div>
        <div class= "nav-list"><li class= "nav-list-item"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span><span> </span><%= link_to "logout", destroy_user_session_path, method: :delete %></li></div>
      </ul>
      <% else %>

      <ul>
        <div class= "nav-list"><li class= "nav-list-item"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><span> </span><%= link_to "Home", root_path %></li></div>
        <div class= "nav-list"><li class= "nav-list-item"><span class="glyphicon glyphicon-link" aria-hidden="true"></span><span> </span><%= link_to "About", home_about_path %></li></div>
        <div class= "nav-list"><li class= "nav-list-item"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span><span> </span><%= link_to "sign up",  new_user_registration_path %></li></div>
        <div class= "nav-list"><li class= "nav-list-item"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span><span> </span><%= link_to "login", new_user_session_path %></li></div>
      </ul>

      <% end %>
    </nav>
  </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
	<div> <%= f.hidden_field :following_id %></div>
	<%= f.submit "Follow", class: "btn btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id = "follow_form">
	<% if current_user.following?(@user) %>
		<%= render 'users/unfollow', user: @user %>
	<% else %>
		<%=render 'users/follow', user: @user %>
	<% end %>
</div>
<% end %>

app/views/users/_stats.html.erb
<% user ||= current_user %>
<div class = "stats">
	<a href ="<%= following_user_path(user) %>">
		<strong id ="following" class="stat">
		<%= user.followings.count %>
		</strong>
		following
	</a>
	<a href ="<%= followers_user_path(user) %>">
		<strong id ="followers" class="stat">
			<%= user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
	<%= f.submit "Unfollow", class: "btn btn-danger follow-btn" %>
<% end %>

app/views/users/edit.html.erb
<div class= "row ">
	<div class="col-md-5 col-md-offset-1">

<h2>User info</h2>

<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>


<%= form_for(@user) do |f| %>

		<samp>Name</samp>
		<%= f.text_field :name %>
		<p> </p>

		<samp>Image</samp>
			<%=attachment_image_tag @user, :profile_image, :fill, 70, 70, format: 'jpeg',fallback: "no_image.jpg", size:'70x70' %>
			<%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
		<p> </p>
		<samp>Introduction</samp>
		<%= f.text_area :introduction %>
		<p> </p>
<%= f.submit 'Update User', class: "btn btn-default" %>
<% end %>
</div>
</div>


<div class="col-md-4 col-md-offset-8">
<p>CopyRight Infratop.inc</p>
</div>

app/views/users/index.html.erb
 <% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<div class= "container">
<div class= "row">
<div class= "col-md-3 ">

 <h2>User info</h2>
<%= attachment_image_tag current_user, :profile_image, :fill, 70, 70, format: 'jpeg',fallback: "no_image.jpg", size:'70x70' %>

		<table class="table">
			<tbody>

				<tr>
					<td>name</td>
					<td><%= current_user.name %></td>
				</tr>
				<tr>
					<td>introduction</td>
					<td><%= current_user.introduction %></td>
				</tr>
				<tr>
					<td><%= render 'stats', user: @user %></td>
					<td><%= render 'follow_form', user: @user  %></td>
				</tr>
			</tbody>
		 </table>
<%= link_to edit_user_path(current_user) do %>
<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_9733" aria-hidden="true"></span> 
<% end %>

<h2>New book</h2>
<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :title, class: "col-xs-12" %>

<h4>Opinion</h4>
<%= f.text_area :body, class: "col-xs-12" %>

<%= f.submit 'Create Book', class: "btn btn-default col-xs-12" %>

<% end %>
</div>

<div class="col-md-9">
	<h2>Users</h2>
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<th> image</th>
				<th>Name</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<td></td>
					<td class="col-md-2"><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "no_image.jpg", size:'50x50' %></td>
					<td class="col-md-2"><%= user.name %></td>
					<td class="col-md-2">
						<% unless current_user?(user) %>
							<div id = "follow_form">
								<% if current_user.following?(user) %>
									<%= render 'unfollow', user: user %>
								<% else %>
									<%= render 'follow', user: user %>
								<% end %>
							</div>
						<% end %></td>
		　　　		<td  class="col-md-3"><%= render 'stats', user: user %></td>
					<td class="col-md-2"><%= link_to  'Show' , user_path(user) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
</div>
</div>
<div class="col-md-4 col-md-offset-8">
<p>CopyRight Infratop.inc</p>
</div>

app/views/users/show.html.erb
 <% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<div class= "container">
<div class= "row">
<div class= "col-md-3 ">
<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, :fill, 70, 70, format: 'jpeg',fallback: "no_image.jpg", size:'70x70' %>

		<table class="table ">
			<tbody>

				<tr>
					<td>name</td>
					<td><%= @user.name %></td>
				</tr>
				<tr>
					<td>introduction</td>
					<td><%= @user.introduction %></td>
				</tr>
				<tr>
		　　　		<td><%= render 'stats', user: @user %></td>
					<td><%= render 'follow_form', user: @user %></td>
				</tr>
			</tbody>
		 </table>

<%= link_to edit_user_path(@user) do %>
<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_9733" aria-hidden="true"></span> 
<% end %>

<h2>New book</h2>
<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :title, class: "col-xs-12" %>

<h4>Opinion</h4>
<%= f.text_area :body, class: "col-xs-12" %>

<%= f.submit 'Create Book', class: "btn btn-default col-xs-12" %>

<% end %>
</div>

<div class="col-md-9">
	<h2>Books</h2>
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @user.books.each do |book| %>
				<tr>
					<td class="col-md-3"><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "no_image.jpg", size:'50x50' %></td>
					<td class="col-md-3"><%= link_to book.title, book_path(book) %> </td>
					<td class="col-md-3"><%= book.body %></td>
					<td class="col-md-3">コメント数: <%= book.book_comments.count %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>


</div>
</div>
<div class="col-md-4 col-md-offset-8">
<p>CopyRight Infratop.inc</p>
</div>

app/views/users/show_follow.html.erb
<div class= "container">
	<div class= "row">
		<div class="col-md-12">
			<h2>Following Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th> image</th>
						<th>Name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @user.followings.each do |user| %>
					<%# if user.id != current_user.id %>
						<tr>
							<td></td>
							<td class="col-md-2"><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "no_image.jpg", size:'50x50' %></td>
							<td class="col-md-2"><%= user.name %></td>
							<td class="col-md-2">
								<% unless current_user?(user) %>
									<div id = "follow_form">
										<% if current_user.following?(user) %>
											<%= render 'unfollow', user: user %>
										<% else %>
											<%=render 'follow', user: user %>
										<% end %>
									</div>
								<% end %></td>
				　　　		<td  class="col-md-3"><%= render 'stats', user: user %>
							</td>
							<td class="col-md-2"><%= link_to  'Show' , user_path(user) %></td>
						</tr>
						<%#else %>
					<%#end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="col-md-4 col-md-offset-8">
	<p>CopyRight Infratop.inc</p>
</div>

app/views/users/show_follower.html.erb
<div class= "container">
	<div class= "row">
		<div class="col-md-12">
			<h2>Follower Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th> image</th>
						<th>Name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @user.followers.each do |user| %>
					    <%# if user.id != current_user.id %>
							<tr>
								<td></td>
								<td class="col-md-2"><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "no_image.jpg", size:'50x50' %></td>
								<td class="col-md-2"><%= user.name %></td>
								<td class="col-md-2">
									<% unless current_user?(user) %>
										<div id = "follow_form">
											<% if current_user.following?(user) %>
												<%= render 'unfollow', user: user %>
											<% else %>
												<%=render 'follow', user: user %>
											<% end %>
										</div>
									<% end %></td>
					　　　		<td  class="col-md-3"><%= render 'stats', user: user %></td>
								<td class="col-md-2"><%= link_to  'Show' , user_path(user) %></td>
							</tr>
						<%#else %>
						<%#end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="col-md-4 col-md-offset-8">
	<p>CopyRight Infratop.inc</p>
</div>